google-ID: ''

menu:
  - {name: 'About', url: 'about'}
  - {name: 'Projects', url: 'projects'}
  - {name: 'Resume', url: 'resume'}
  - {name: 'Contact', url: 'contact'}

social:
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/stephenwdunn2/'}
  - {icon: 'github', link: 'https://github.com/Dunnszn'}
  - {icon: 'envelope', link: 'mailto:vytalz@hotmail.com'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
  sharing_button_prompt: 'Share this page'
  related_posts: 'Related posts'
  post_date_prefix: 'Written on'
